spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: system
    password: hr
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    schemas: KINDRED
    default-schema: KINDRED
  messages:
    basename: i18n/messages
  application:
    name: social
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: system
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: KINDRED

server:
  port: 7070

token:
  secret: mysuperlongsecretk334eythatismorethan32chars
  time: 30d